services:
  app:
    build:
      context: ./docker/php
    container_name: prestamo_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - prestamo_red

  nginx:
    image: nginx:latest
    container_name: prestamo_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - prestamo_red

  mysql:
    image: mysql:8.0
    container_name: prestamo_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestamo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: prestamo_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prestamo_red

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: prestamo_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - prestamo_red

  node:
    image: node:22
    container_name: prestamo_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bash -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    networks:
      - prestamo_red

  composer:
    build:
      context: ./docker/php
    container_name: prestamo_composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["composer"]
    networks:
      - prestamo_red

networks:
  prestamo_red:

volumes:
  mysql_data:
